@rootUrl=http://localhost:7777
@userID=5d57002a-5b62-4b59-abd6-1cb3d326ccfd

POST {{rootUrl}}/api/v1/users
Content-Type: application/json

{
    "username" : "stey",
    "email" : "mail@mail.sru"
}

### GET

GET {{rootUrl}}/api/v1/users/{{userID}}

### CREATE PROJECT

POST  {{rootUrl}}/api/v1/projects
Content-Type: application/json

{
    "name" : "test",
    "end_date" : "25.01.2024"
}

### GET PROJECT

GET {{rootUrl}}/api/v1/projects/92ee953c-3cec-4410-9bb4-5797a95c4b2a