server:
  port: 7777

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    disable-swagger-default-url: true
    operations-sorter: method
    urls:
      - name: Jenjetsu Todo resource
        url: /api-docs/swagger-config.yaml
  

spring:
  application:
    name: Jenjetsu-todo
    dashboard:
      invite-expiration-time-hours: 48
  datasource:
    username: Stey
    password: 1228
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5001/jenjetsu_database?characterEncoding=utf8
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/jenjetsu-realm
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false

topic:
  mail-topic: test-topic 
