server:
    port: 7777

spring:
    datasource:
        username: Stey
        password: 1228
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5001/jenjetsu_database
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect